### ISSUE TITLE
Styles.Styles unable to be imported if `./src/styles` is the source path.

### ISSUE THREAD

**Issue by sunwukonga** [wintvelt/elm-dropdown#12]
On Archlinux I needed to changed the capitalization of the styles directory for `import Styles.Styles as Styles` to work.

i.e. from `src/styles` to `src/Styles`

Otherwise I got the error: 
```
    Need to add a source directory or new dependency to elm-package.json
```

**Comment by sunwukonga** [comment]
Same with the `examples/pure` and `examples/stateful` directories.
`examples/pure` -> `examples/Pure`
`examples/stateful` -> `examples/Stateful`

**Comment by wintvelt** [comment]
Thanks for pointing this out. Capitalized the referenced folder names.
